# Generated by Django 3.1.7 on 2021-05-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='media/')),
                ('club_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_fname', models.CharField(max_length=100)),
                ('player_lname', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='media1/')),
                ('jersey_number', models.IntegerField()),
                ('player_country', models.CharField(max_length=100)),
                ('total_matches', models.IntegerField(default=0)),
                ('total_runs', models.IntegerField(default=0)),
                ('hundreds', models.IntegerField(default=0)),
                ('half_centuries', models.IntegerField(default=0)),
                ('highest_score', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
