# Generated by Django 3.1.7 on 2021-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='highest_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='total_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
