# Generated by Django 3.1.7 on 2021-05-18 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210516_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
    ]
