# Generated by Django 3.1.7 on 2021-05-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20210518_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='result',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2',
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='team.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='team.team'),
            preserve_default=False,
        ),
    ]
