# Generated by Django 3.1.7 on 2021-05-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210518_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
