# Generated by Django 3.1.7 on 2021-05-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
